apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 81         
      targetPort: 81   
      nodePort: 30081  
