apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 81        
      targetPort: 81   
