apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: final
type: Opaque
data:
  DBHOST: bXlzcWwtY29udGFpbmVy
  DBUSER: cm9vdA==
  DBPWD: cHc=
  DATABASE: ZW1wbG95ZWVz
  AWS_ACCESS_KEY_ID: QVNJQVFFRE5WUlNTUDRFSUlCM1U=
  AWS_SECRET_ACCESS_KEY: WlJiMktEbEVrTU5PdGxGUVhCc0lvSnNTRTBXSHB3TXhTQ3Ird1JSUg==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVESWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lEZUMzRkcxb3NaQTBzLzVN
VnpsYmRkVnJ4QU1veDJyWFdDalEwL3VQSWF2QWlFQTk3dnFzN2VjSnozWFoxdnFqT0toR0JEbDVl
WU9nTVBYYUtXdmpJV3NTNUVxc1FJSXEvLy8vLy8vLy8vL0FSQUFHZ3d3TURnNE1UazVNelkwTWpB
aURKR3Y2TkNkQVdySGl0L214eXFGQWpoZG1jdVhqQmo2eHEvclVrNXNzaU5WcitEaG1VQlExeXo4
ZjJuZEJoTjdzNUY4UjFrR05uQXo3NENaUUZlL08rY0ZiTzhKcTBIcXlYdGQxWVlqUkJSams3ZmNw
VldxamVsaHVkY3pBMHJkdncwcXlTcHNWR2RjQzEvL1pqNGExNEpSTWw0djJnTmhyU3JCUTV0VGNx
NTFZNThvVmpnY0FCOUdTbGEvaFZZRENhTUVIMlRKNmJSS1lzVTI1OVc0NllEK21XVHJialhBT1dJ
OW90OGtEenZTY3B1OTJyRVdKeGk2dnRKS0MvN1l4TEFTSFV3QnJ4ek5iL3F6RnZBdXJxQmI5MkNt
b0hBc2l3SDZuTUFHenIxTDZqV0d5Uk1jWVBNZzlxK3RZb1hpUTFPejBRZEwvN1NHZEVINWlkcGxk
YmdEYzlmY2d4UnN0ZE13L1JSQzJTN3hEQlNzTHpEdWd1Qy9CanFkQWZ0ZWZyQys2anZsVDFmNXRF
WEkzRG5wcTJyWTJzU1pRbmJnYmpQNjhvK3IrWS80cjh6U3pjbGRRbnRlT1hkMzQ1SmZsWHFLRitG
MXZIVUpvZmdZSFJFejRMMFdPWG00c1g3czRKdVBicWZLZHNjcSs1SGd5WGRCR3FlVkxEYWpzVlFO
VmFRbUM3TVA4ZUQ1VmxkYXZFVWJXZFl5bE0xbk5nS3hTUVo5d2JOTHVhamhDU1YraEx5eXQvZkxw
SUl1VU1EcmtJZjduK1E3MWpCRWs3Zz0=
  
---

apiVersion: v1
kind: Secret
metadata:
  name: ecr-pull-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ZXdvSkltRjFkR2h6SWpvZ2V3b0pDU0l3TURnNE1UazVNelkwTWpBdVpHdHlMbVZqY2k1MWN5MWxZ
WE4wTFRFdVlXMWhlbTl1WVhkekxtTnZiU0k2SUhzS0NRa0pJbUYxZEdnaU9pQWlVVlprVkU5dFZq
VlRibVJhVjBkNGVsbHFTa2RoTUd4eFlqSnNWRTFIZUVwWGJXczFZVEZzV0ZSdWFHdFNNSEJEV1Zj
d05WWnRTWGRPV0doU1ltMW9SVlZxU1RWalJsSkpVMjAxYUdGclNuaFRNM0JyVjFaS05sb3phRlZX
Vld0NlZXMXdRMkZWTVZoVGJrSmFWakZ3UkZScldrZFdNVlYzVm10V1dtRXhXbGxVTUZwcVRXeFdj
V0ZJVWxCVFJuQkdWbFJDYTFsV1NYcGFSekZVWWxWcmVsWnNhRzVsVlRsWVlrZHdWMVl6VWtwWFYz
UkhWbFpXV1ZwRVdrOVNWMmN4V2tWU1ExVldjSE5hUm14YVlsZFJNbHBWV2s5Tk1WcDFWV3RLVkZk
Rk5ERmFSbEp2Vkd4d1ZWcEdjRlZpUlVwVlZrVk5OVTVGTlZaV2EzUlhZa1pLY2xsVVFYZE5iSEJ5
WVhwV1ZGSllaRFZXUlZKVFZVWmFWMUpyWkZSV1JWcEVXa1ZhYzFSV2NGaE5WRTVNVFZWYWIxcEdW
a2RVUmxWNldUTndhV0pGTURCWGJGcDNZa1V3ZUZkcVNsTk5WVFZ5V1cxMFUxSXhiM2RUV0docllX
dHdNRll5ZUZwTmF6VnlUMVphVlZKVVZqWmFSekYzVTBkU1ZtUkZTbE5XVkZFeFZqQldVMlJIVWpa
WGEzUlNaVmhTUkZwWE1EVlVSMFp5WkhwR1YxSjZWbFZXVldNd1pVWk9ObHBJYkdwU1IzaHdWbFZX
VW1Wc2NIUmtSM0JXVjBoQ2VWVXhWa2RXVlRsRldrZDRWV0V6UWs1VE0yczFUa1pHVmxack1XeGhh
MHBKVkdwS1UxWldVblJPVmxaYVZqTmpNVlJWVWtka01XeFlWVzV3YUdWcldrbFdSekZIVkRKT1Ix
cEhjRlZOVlRWeVdUSndibVJzYkZoVWJUVlRVMGRvVGxkclZuZFRWbHBHWlVWMFVsWnJXbGxaYTJO
NFkxZFNkVk50TlZkU1YxSnZWbFJLVDFNeVJuVlRhMUpoVWpCd2RWWnNXbGROYlVwSFkwZEdWVlpZ
VWxGVmFrSnpWVVpHTmxwR1VrNVRSM2Q2V1ZWa2ExTlhSa2hPVkVKTVRVVmFXVmRXVlRGV1JsRjZX
a1pzVUZWNmJIUmFWM00wVFcxS1YxTnJaRk5YUlRWUldsWldNRTVWTlhSU2JURnNZbFUxZFZZd1Rq
QlJNRFZXVDFob1RVMXJOVTVVVnpFMFVXeEZkMXBGWkZKTlJHeHpWakJhYjJGSFRsWmlSM1JXVFVk
U1VGVXljR3RpUjAxM1lVaHdXRmRGU25CWFZtUjNXVlpXY0U5WGFGQlNWRVp4V2xab2FrMUZNSGRp
U0ZaT1lsaG9ZVmw2UWtkalJsWkdZVWhTVUZKRldsWlpiWGhhVFRGd05scElRbUZTYkZsNVZGVk5O
VlZXV1hsa1JVNU9VMFphUkZSdWNHOVNNREZZV2tSV1RsZEhVblJVTVZaU1RrWmtkR0ZHWkdwV2Vs
WnlXa2Q0UjFSVk5WbFRiRlpxVmpOb05GUlljRTlUVjBsM1UyeGtUbVZVYkVSWk1XaExUVVphVlZw
SVRtRk5ibEpFVld4V1QxWnNUa2RoZWtKVlpXczFWRmxyV21wTlZsWldUbGN4VlZaV2J6QlpWbFV4
VjFaT1IxUnJlRTlpYlhkNlZWWmtNR0l5U1hkUFdHeE9WbXhWTVZsc1ZuZE5hekZZWkVSV1dtSnJX
azlXYTFwTFlteFZlVmR0ZEdsU2ExcEdWbXBLYjJWR2EzbFNhekZZWVRGdmVGWnFSa2ROTWtwV1lr
Wk9hVTFHV1hwVU1XaFNUV3hzTmxOcVRsUmhNMDQyVmpGb1JrMXRVbGRqUmxwU1ZsZDRNRlY2U25a
TmJFcHlZVWMxYUZJd1drbFpNR1J6VFcxR1ZtSkdhRmRXTTBKRVZrUkthMkZHY0hWUmJHeE9VbTVD
UjFSV1ZqTk5iRXBIVlZSQ2JHSnJiSGxaYWs1eVRVWndObHBHY0dwWFJVcE1Xa2N4UjJNeFdsVmFS
RkpPVmpBd2VGWnNhR3RsUm10NVVsaG9ZVll5YUVOWFYzaHJVa1UwZDJOSVRsUmhNMmh5V1ZWTk5W
ZEdUbkpXVkVKVlpXdEtWRlV5Tlhka2JIQlpWMnRvVFUweWFIWldWbU0xWlZkU1ZWUnROVlJoYTFw
SFZURldXbVZYVmtoWGJIQlFWakExV2xkdGNHOWpWMUpZWWtST1ZXRllVblJYVjNoclYxVTVXRTFV
VW14VFIxRjZWVmR6TUdWR1ZuVlhiV2hPWVRBMVJsVnFTbTlVYXpSNVpVUktUVTFzYTNsWFdIQkxZ
ekZhY21OSFJsWldhM0JEVjJ4U2IySnRTbkZSYkVKb1lXczFkRll4VmtabFJsWlZVMVJPVW1KRldu
cFdiRkpMVVd4a1dWcEhiRk5XVkVKNVdWWlNTazFyTVZWaVJWWnBVbFpLVlZkWE1ERlVhM2cyVjI1
S1RsSkZSWGRWYTJRd1RVZFdTV0pGTldsTmFrWlpXV3hrYzFWc1VrVlhhMUpRVjBaYVlWbFZaRkpP
UmtsNFVtNUthV0pZYURaVmJGSnJVbFpPY2xWdWNGTlNNSEJ3V1cxME5GWkhWa2xWVkVaVlVtdHdU
bFpzVGpCbGJVWkpVbTVhV2sxRk1IcFphMVY0VTFad1ZWWllTbXRTTUhCb1ZGWm9RMlZIVm5WU1ZG
WlFWbnBXZEZwRmFIZGxiRkpKVm10YWFrMVdhM3BWVkVreFRVVTFkR1ZFU21wU1ZrcG9WVlJHUjFS
dFJYZE9WbHBwVFc1Q05GUldhRzlWYkU1SVUydGthMkV6VGpWVU1XUjNUVVprU0U5V1RtdFdNR3Q2
Vld0U1lWSlZOSGRXV0doUFlsVTFkVlV5ZUhKTk1VNXhVVlJLVW1WWVVscFdiWFJIVlVkS05XUkhh
RlJOTUhCdlZFaHdRMVJzVGxaUFZUbG9VbFphY2xkV2FFdE5Wa1Y2VjIxNGFWSXdOVzlWYlRGSFlq
SldkRmR1Y0d4aWF6VTJWa1pXZWs1V1ZsUmtSa0pQVWxSc05WcEhjRUprTVd4d1QxUlNWRlpXV2xo
V2JYUkxVekZHVjFOWWJGSk5iRlkxVlZaU1FtUXhUa2RVYkZwclRUQmFXbHBGYUhkU2JVWlpWV3BH
VkdGNlZucFdNVlozVlcxV1NHTkhPVmhpUmxvMVdsWm9hMVpYVFhsUFZGWlRVMFp3U1ZaVVRrOU5i
RVpZVjIxMFdsWjZSVEZhUldodVRXMVNWVkZyTVZOU1YyaFRWMjV3YTFSSFRsVmlTRnBzWVROU2Mx
bFdWWGhUTWtwWVZHNU9VRkpZUWtOWGEyaENZMjFPY1ZOWVdsUlNSVEUyVmpKNFYyRkZNVVZUYm5C
VVlrVnJNVlZxVG5KTlZuQnlZek5zVTFOR2NGRlZiWFJYWVcxR05XTXpTbXRXVjJoUlZHMXplRkV4
V2tobFNGSnFVbXRhWVZWclVsTk9WMDQyV2tkMFZHRnNXbUZaYTJSM1ZrWlNTRTFJV2xWU1ZrcEVW
a1ZvYjAxc1NrWk5WWFJyVVROU1NsWldWVFZYYkVZMVpFWmtVRk5HU2tsWmVrcHJWVmRHU1dOSVdt
bFdSVm8yVmxaV1UxSnJkM3BYYWxKU1YwaEJkMVJWV25OUmJGcFlXa1ZzVGsxR1NYZFpiR2h1VGxk
S1dGTnFTbFZTVlRVMlYxaHdiMkpWTVVsVmJrcHBVa1p3Y0ZreFVrTlpWMVpHVTIxb2FXSldXakpV
TUZaMlRVZFNSbFJ0TlZkaGJWSjVWbFJDYTFOc1JsbFVWRVpYVTBadmVWVnVjRVpOYlVaeFZXeG9V
Rkp1UVhsVVZWcFBVakZ3UmxadVpGUlRSVW8xVjJwS2MyUnNSWHBhUlRscVVtdEtVbFV5Tlhka1Js
bzJXa1JXVjJFeFdUQldWbWhMWXpGWmVsSnNTbGRTTURCNVZrVmFSMUl3ZERWUFZXUlZWbXhXTmxw
VlpFdGxSazE1Vm10MGExWXlUVFZUVjJ3ellWWndTRkpxUWxwV00xSnpXbFpPU2s1cmJISlNiRXBU
VmxWd1ExVXdaRzlOTWtwVlVXeHdXbFpYZUZWVk1qRlhWVEpTUm1OSVVrOVdlbEkwVlc1d1lVMVhU
bGhXYlhob1RWZG5lRmxxUm05WFZsWklWbFJHVjFaV2NIRlhiRkp6VlRKT1ZWb3pXazVXUmtsNlZW
WldSMUZzVGtWVmFrNWhZVEJhWVZVeWREQmtiR1J5WWtjNWEySlZOVkJWVmxwSFlXeEplVTlWYUZC
VFIxSndWbFpXYzFFeFJsWlZhMDVwVFVWd2RWbFVUa2RpTWtWNVlrVm9VRmRIVGpOVlYzUkxUVEZL
V1ZwRmJHRk5WM2hNVmpGV2MxbFdUbFpTYkdoWFZsWktSRlZXVmxkTlZsSldVMnRhVTFaV1NrdFpW
elYzVGtadmVVMVZiRlJTTURReVZsWlNjMWRXY0ZsaVJFcFdWbGQ0UkZWc1ZuTlJhelIzVGtSQ2Ey
RXdhM3BaYlhCdllqQTBlRkZ1UWxwaVYxSXlWRlJPUjFVeFduTlVhM2hQVWpOb1ZWbFhNWGRWTWxa
V1lrWndXRkpGY0ZkVVJFNUxUVEIzZUZOWVdtaFdiRnBVVmpKNFExUnNTWGRoUlVwT1pXc3hNbFJ0
TURSTlJrVjVWMjV3WVUwd2NGbFpWbU40VTBaS1ZrOVZWbGhXUjNNd1dUQmpOVTVHYTNsU2JGSlBU
VEpTVUZSdGRFWlBWV3h3WkRKc2EySldXalZaZWtwelpHMUtjRk5VV2twaGEyeHdWRVZPUzAxSFZs
bFJiWGhLWVcwNWNGVnJWa2RXVmtaWFQxVjRVMVp0ZEhCVVJVNUxZa2RXU1ZGdVFtcGlWVmwzV1Za
ak5XUlZiSEZpTTJoUFpXeEZkMVJZY0ZabGF6VTJXWHBDYlZWVU1Ea2lDZ2tKZlFvSmZRcDk=
