apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: final
type: Opaque
stringData:
  DBHOST: mysql-container
  DBUSER: root
  DBPWD: pw
  DATABASE: employees
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_SESSION_TOKEN: I
---

apiVersion: v1
kind: Secret
metadata:
  name: ecr-pull-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-dockerconfig>